name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # download repo
    - uses: actions/checkout@v4
    # setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    #install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2
    # setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew
    # Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew webTest
    # Archive Test Result
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: Cucumber Report
        path: reports   
    # Deploy to Github Pages
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        # PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # PUBLISH_DIR: reports
        token: ${{ secrets.GITHUB_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        folder: reports
        target: gh-pages
    
          
